name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Debug Info
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Package.json contents:"
        cat package.json
        
    - name: Install dependencies
      run: |
        npm config set package-lock false
        npm install --no-package-lock --no-audit --no-fund --verbose
        echo "Dependencies installed successfully"
        echo "Node modules size: $(du -sh node_modules)"
        
    - name: Build
      run: |
        echo "Starting build..."
        npm run build
        echo "Build completed"
        echo "Dist folder contents:"
        ls -la dist/
        echo "Dist folder size: $(du -sh dist)"
        echo "Checking for key files:"
        if [ -f "dist/index.html" ]; then echo "✅ index.html exists"; else echo "❌ index.html missing"; fi
        if [ -d "dist/assets" ]; then echo "✅ assets folder exists"; ls -la dist/assets/; else echo "❌ assets folder missing"; fi
        echo "Full dist tree:"
        find dist -type f -exec ls -la {} \;
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
